
#use_modular_headers!

platform :ios, '10.0'

target 'DoraemonKitPlugins_Example' do
  pod 'DoraemonKit/Core'
  pod 'DoraemonKitPlugins', :path => '../'
  
  target 'DoraemonKitPlugins_Tests' do
    inherit! :search_paths

  end
end
